// USER
export const FETCH_USER = 'FETCH_USER'
export const SUCCESS_USER = 'SUCCESS_USER'
export const FAILED_USER = 'FAILED_USER'

// KONTAK DARURAT
export const FETCH_CONTACT = 'FETCH_CONTACT'
export const RECEIVE_CONTACT = 'RECEIVE_CONTACT'
export const FAILED_CONTACT = 'FAILED_CONTACT'
